### ISSUE TITLE
This feels like assembly but backwards

### ISSUE THREAD

**Issue by Hornet07** [darealvenum/venumLang2#1]
Why do you have `var` then type name?
Why do you have to explicitly use `write`/`load`?
Why are the statements all backwards? It's harder to read.
For example why `x y ==` instead of `== x y` or better yet, `comp x y` to match the direction the `write` and `load` keywords are going.
How would you even write more complex operations with this syntax? (e.g. `(x ^ (y << 1)) >> 1) ^ (z << 1)`)

This just feels inconvenient

**Comment by darealvenum** [comment]
it feels backwards because it is, refer: https://en.wikipedia.org/wiki/Reverse_Polish_notation

you have to explicitly use write/load because it  is stack bases, so you first push the addr of variable and then do your next operation.

as for ur last point.... youll just have to write everything one by one for now : >
